build vue:
  image: node:8
  stage: build
  before_script:
    - cd vue-client
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - vue-client/dist
  only:
    - master

build react:
  image: node:8
  stage: build
  before_script:
    - cd react-client
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - react-client/build
  only:
    - master

