test:
  image: node:8
  stage: test
  before_script:
    - yarn
    - yarn global add jest
  script:
    - jest
  only:
    - master

vue build:
  image: node:8
  stage: build
  before_script:
    - yarn
  script:
    - yarn vue:build
    - yarn react:build
  artifacts:
    expire_in: 1 week
    paths:
      - packages/vue-client/dist
      - packages/react-client/build
  only:
    - master
