vue test:
  image: node:8
  stage: test
  before_script:
    - yarn
  script:
    - npm yarn vue:test
  only:
    - master

# vue build:
#   image: node:8
#   stage: build
#   before_script:
#     - cd packages/vue-client
#   script:
#     - npm install --progress=false
#     - npm run build
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - packages/vue-client/dist
#   only:
#     - master

# vue electron build:
#   image: node:8
#   stage: build
#   before_script:
#     - cd packages/vue-client
#   script:
#     - npm install --progress=false
#     - npm run electron:generate-icons
#     - npm run electron:build
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - packages/vue-client/dist_electron
#   only:
#     - master

# react test:
#   image: node:8
#   stage: test
#   before_script:
#     - cd packages/vue-client
#   script:
#     - npm install --progress=false
#     - npm run test
#   only:
#     - master

# react build:
#   image: node:8
#   stage: build
#   before_script:
#     - cd packages/react-client
#   script:
#     - npm install --progress=false
#     - npm run build
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - packages/react-client/build
#   only:
#     - master

# server test:
#   image: node:8
#   stage: test
#   before_script:
#     - cd packages/server
#   script:
#     - npm install --progress=false
#     - npm run test
#   only:
#     - master

