language:
  node_js
node_js:
  - 10
sudo: required
before_install:
  - npm install -g node-gyp
  - mkdir -p "$HOME/.yarn/bin"
  - curl -L -o "$HOME/.yarn/bin/yarn" https://github.com/yarnpkg/yarn/releases/download/v1.15.2/yarn-1.15.2.js
  - chmod +x "$HOME/.yarn/bin/yarn"
  - export PATH="$HOME/.yarn/bin:$PATH"
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
install:
  - yarn global add codecov
  - yarn global add jest
  - yarn
  - cd server && yarn && cd ..
script:
  - jest
  - codecov
