language:
  node_js
node_js:
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - yarn global add codecov
  - yarn global add jest
  - cd server && yarn && cd ..
script:
  - jest
  - codecov
