version: '3.1'

services:
  kupi-mongo:
    image: mongo:3
    env_file:
      - ./private/mongo.env
    volumes:
      - ./private/mongo/db:/data/db
    ports:
      - 127.0.0.1:27018:27017

  kupi-react:
    image: node:8
    links:
      - kupi-server
    ports:
      - 127.0.0.1:8041:8041
    volumes:
      - ./:/app
    working_dir: /app/packages/react-client
    command: sh -c 'yarn && yarn docker'

  kupi-server:
    image: node:8
    volumes:
      - ./:/app
    links:
      - kupi-mongo
    depends_on:
      - kupi-mongo
    ports:
      - 127.0.0.1:8040:8040
    working_dir: /app/packages/express-server
    command: sh -c 'yarn && yarn docker'
