version: '3.1'

services:
  kupi-terminal-mongo:
    image: mongo:latest
    env_file:
     - ./private/mongo.env
    volumes:
      - ./private/mongo/db:/data/db
      # - kupi-terminal-mongo-volume:/data/db
    ports:
      - 127.0.0.1:8049:27017
    # command: mongod --smallfiles --logpath=/dev/null # --quiet

  kupi-terminal-client:
    build: ./react-client
    ports:
      - 127.0.0.1:8050:8050
    volumes:
      - ./react-client:/react-client
      - /react-client/node_modules
    command: yarn start

  kupi-terminal-server:
    build: ./server
    volumes:
      - ./:/app
      - /app/server/node_modules
      - /app/react-client/node_modules
    links:
        - kupi-terminal-mongo
    depends_on:
        - kupi-terminal-mongo
    ports:
      - 127.0.0.1:8051:8051
    command: yarn docker
    # sh -c 'npm i && node server.js'



# volumes:
#   kupi-terminal-mongo-volume:
