version: '3.1'

services:
  kupi-mongo:
    image: mongo:3
    env_file:
     - ./private/mongo.env
    volumes:
      - ./private/mongo/db:/data/db
    ports:
      - 127.0.0.1:27018:27017

  kupi-react:
    image: node:8-alpine
    ports:
      - 127.0.0.1:8041:8041
    volumes:
      - ./react-client:/react-client
      # - /react-client/node_modules
    working_dir: /react-client
    command: sh -c 'yarn && yarn docker' # yarn start

  # vue:
  #   # build: ./vue-client
  #   image: node:8-alpine
  #   ports:
  #     - 127.0.0.1:8042:8080
  #   volumes:
  #     - ./vue-client:/vue-client
  #     # - /vue-client/node_modules
  #   working_dir: /vue-client
  #   command: sh -c 'yarn && yarn start' # yarn start

  kupi-server:
    build: ./server
    volumes:
      - ./:/app
      - /app/server/node_modules
      - /app/react-client/node_modules
      - /app/vue-client/node_modules
    links:
        - kupi-mongo
    depends_on:
        - kupi-mongo
        - kupi-react
    ports:
      - 127.0.0.1:8040:8040
    command: yarn docker
    # sh -c 'npm i && node server.js'



# volumes:
#   kupi-terminal-mongo-volume:
