version: '2'

services:
  # client:
  #   build: ./client
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/client
  #     - /client/node_modules

  server:
    build: ./
    restart: always
    ports:
      - "8051:8051"
    volumes:
      - ./:/app
      # - /server/node_modules
      # - /client/node_modules
    # links:
    #     - kupi-terminal-mongo
    # depends_on:
    #     - kupi-terminal-mongo
    # command: nodemon index.js

  # kupi-terminal-mongo:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGO_INITDB_ROOT_USERNAME=user
  #     - MONGO_INITDB_ROOT_PASSWORD=pass
  #     - MONGO_INITDB_DATABASE=terminal
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #     - 27017:27017
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet
