version: '3.1'

services:
  kupi-terminal-client:
    build: ./react-client
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./react-client:/react-client
      - /react-client/node_modules
    command: yarn start

  kupi-terminal-server:
    build: ./server
    volumes:
      - ./:/app
      - /app/server/node_modules
      - /app/react-client/node_modules
    links:
        - kupi-terminal-mongo
    depends_on:
        - kupi-terminal-mongo
    ports:
      - 127.0.0.1:8051:8051
    command: yarn docker
    # sh -c 'npm i && node server.js'

  kupi-terminal-mongo:
    image: mongo:latest
    environment:
      # MONGO_DATA_DIR: /tmp/db
      # MONGO_LOG_DIR: /tmp/null
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 127.0.0.1:27017:27017
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
